---
- name: Install tripwire
  apt: pkg=tripwire state=installed update-cache=yes
  register: tripwire_install
  tags:
    - apt

# Set Config
- name: Install tripwire
  command: sudo twadmin --create-polfile /etc/tripwire/twpol.txt; sudo tripwire --init;sudo tripwire --check

- name: Install Mailutils
  apt: pkg=mailutils state=installed update-cache=yes
  register: mailutils_installed
  tags:
    - apt
  #TO-DO: Cron Job to Email Tripwire Reports
  #cron: 30 3 * * * /usr/sbin/tripwire --check | mail -s "Tripwire report for `uname -n`" vishalhlall@gmail.com
